#!/usr/bin/env python3

import sys
import argparse
from PIL import Image, ImageChops


def process_command_line(argv):
    """Process command line invocation arguments and switches.

    Args:
        argv: list of arguments, or `None` from ``sys.argv[1:]``.

    Returns:
        args: Namespace with named attributes of arguments and switches
    """
    #script_name = argv[0]
    argv = argv[1:]

    # initialize the parser object:
    parser = argparse.ArgumentParser(
            description="Compare two images to verify if image data " \
                    "of both are identical."
                    )

    # specifying nargs= puts outputs of parser in list (even if nargs=1)

    # required arguments
    parser.add_argument('image1',
            help="Image 1 to compare."
            )
    parser.add_argument('image2',
            help="Image 2 to compare."
            )

    # switches/options:
    #parser.add_argument(
    #    '-s', '--max_size', action='store',
    #    help='String specifying maximum size of images.  ' \
    #            'Larger images will be resized. (e.g. "1024x768")')
    #parser.add_argument(
    #    '-o', '--omit_hidden', action='store_true',
    #    help='Do not copy picasa hidden images to destination directory.')

    args = parser.parse_args(argv)

    return args

def main(argv=None):
    args = process_command_line(argv)
    im1 = Image.open(args.image1)
    im2 = Image.open(args.image2)
    identical_images = ImageChops.difference(im1, im2).getbbox() is None
    if identical_images:
        print("Images are identical.")
    else:
        print("Images are different.")

    return 0


if __name__ == "__main__":
    try:
        status = main(sys.argv)
    except KeyboardInterrupt:
        print("Stopped by Keyboard Interrupt", file=sys.stderr)
        # exit error code for Ctrl-C
        status = 130

    sys.exit(status)
