#!/bin/bash

baselayer=$1
upperlayer=$2
outputiconset=$3

echo "Base Layer:  $baselayer"
echo "Upper Layer: $upperlayer"
echo "Output:      $outputiconset"

mkdir $outputiconset

this_icon="icon_512x512@2x.png"
gm composite $upperlayer/$this_icon $baselayer/$this_icon $outputiconset/$this_icon
this_icon="icon_512x512.png"
gm composite $upperlayer/$this_icon $baselayer/$this_icon $outputiconset/$this_icon
this_icon="icon_256x256@2x.png"
gm composite $upperlayer/$this_icon $baselayer/$this_icon $outputiconset/$this_icon
this_icon="icon_256x256.png"
gm composite $upperlayer/$this_icon $baselayer/$this_icon $outputiconset/$this_icon
this_icon="icon_128x128@2x.png"
gm composite $upperlayer/$this_icon $baselayer/$this_icon $outputiconset/$this_icon
this_icon="icon_128x128.png"
gm composite $upperlayer/$this_icon $baselayer/$this_icon $outputiconset/$this_icon
this_icon="icon_32x32@2x.png"
gm composite $upperlayer/$this_icon $baselayer/$this_icon $outputiconset/$this_icon
this_icon="icon_32x32.png"
gm composite $upperlayer/$this_icon $baselayer/$this_icon $outputiconset/$this_icon
this_icon="icon_16x16@2x.png"
gm composite $upperlayer/$this_icon $baselayer/$this_icon $outputiconset/$this_icon
this_icon="icon_16x16.png"
gm composite $upperlayer/$this_icon $baselayer/$this_icon $outputiconset/$this_icon
