#!/bin/bash

thispwd=`pwd -P`

if [ -e dist/dmg_dir ]; then
    echo "dist/dmg_dir already exists"
else
    echo "creating dist/dmg_dir"
    mkdir dist/dmg_dir
fi

cp -a dist/Cellcounter.app dist/dmg_dir/

if [ -e dist/dmg_dirApplications ]; then
    echo "Alias to /Applications already exists"
else
    echo "Creating alias to /Applications"
osascript <<END_OSASCRIPT
tell application "Finder"
    make alias file to folder (posix file "/Applications") at (posix file "$thispwd/dist/dmg_dir") with properties {name:"Applications"}
end tell
END_OSASCRIPT
fi

hdiutil create dist/Cellcounter.dmg -volname "Cellcounter" -srcfolder dist/dmg_dir
