#!/bin/bash

# add current git hash to VERSION_STR in const.py, saving backup file
githash=(`git rev-parse --short HEAD`)
cp cellcounter/const.py cellcounter/const.py.bak
perl -i -pe "s/(VERSION_STR = \")[^\"]+/\1$githash/g" cellcounter/const.py

# activate virtual environment for python
source virt/bin/activate

# build app using py2app
python3 setup.py py2app

# move back original const.py file
mv cellcounter/const.py.bak cellcounter/const.py
