"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['cellcounter/cellcounter.py']
APP_NAME = 'Cellcounter'
VERSION = '0.1.0'
DATA_FILES = [
        'cellcounter/topen32.png'
        ]
OPTIONS = {
        'iconfile':'cellcounter/cellcounter.icns',
        'plist':{
            'CFBundleName':APP_NAME,
            'CFBundleDisplayName':APP_NAME,
            'CFBundleGetInfoString':'Count cells in biological images',
            'CFBundleIdentifier':'com.itsayellow.osx.cellcounter',
            'CFBundleVersion':VERSION,
            'CFBundleShortVersionString':VERSION,
            'CFBundleDocumentTypes':[],
            'NSHumanReadableCopyright': u"Copyright © 2017, Matthew A. Clapp, All Rights Reserved"
            },
        }

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
