#!/bin/bash

# Copyright 2017-2018 Matthew A. Clapp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

baselayer=$1
upperlayer=$2
outputiconset=$3

echo "Base Layer:  $baselayer"
echo "Upper Layer: $upperlayer"
echo "Output:      $outputiconset"

mkdir $outputiconset

iconset_files=(\
    "icon_512x512@2x.png" "icon_512x512.png" \
    "icon_256x256@2x.png" "icon_256x256.png" \
    "icon_128x128@2x.png" "icon_128x128.png" \
    "icon_32x32@2x.png" "icon_32x32.png" \
    "icon_16x16@2x.png" "icon_16x16.png" \
)

for this_icon in ${iconset_files[*]}; do
    echo $this_icon
    gm composite $upperlayer/$this_icon $baselayer/$this_icon $outputiconset/$this_icon
done
