#!/bin/bash

# Copyright 2017-2018 Matthew A. Clapp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# simple usage info
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <baselayer>.icns <upperlayer>.icns <output>.icns"
    echo ""
    echo "  Composite each member image of <baselayer>.icns with"
    echo "  each member image of <upperlayer>.icns into output <output>.icns"
    exit
fi

baselayer_icns=$1
upperlayer_icns=$2
output_icns=$3

echo "Base Layer:  $baselayer_icns"
echo "Upper Layer: $upperlayer_icns"
echo "Output:      $output_icns"

# create safe temp dir
mytempdir=$(mktemp -d "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")

echo $mytempdir

# get just filenames with no dirs preceding
baselayer_icns_base=`basename "${baselayer_icns}"`
upperlayer_icns_base=`basename "${upperlayer_icns}"`
output_icns_base=`basename "${output_icns}"`
#baselayer_icns_base=${baselayer_icns##*/}
#upperlayer_icns_base=${upperlayer_icns##*/}
#output_icns_base=${output_icns##*/}

# get version of filenames with .iconset suffix instead of .icns
baselayer_iconset=$mytempdir/${baselayer_icns_base%.*}.iconset
upperlayer_iconset=$mytempdir/${upperlayer_icns_base%.*}.iconset
output_iconset=$mytempdir/${output_icns_base%.*}.iconset

echo $baselayer_iconset
echo $upperlayer_iconset
echo $output_iconset

# create iconset dirs in temp dir, and make empty dir for output iconset
iconutil -c iconset -o $baselayer_iconset $baselayer_icns
iconutil -c iconset -o $upperlayer_iconset $upperlayer_icns
mkdir $output_iconset

# all iconset member files
iconset_files=(\
    "icon_512x512@2x.png" "icon_512x512.png" \
    "icon_256x256@2x.png" "icon_256x256.png" \
    "icon_128x128@2x.png" "icon_128x128.png" \
    "icon_32x32@2x.png" "icon_32x32.png" \
    "icon_16x16@2x.png" "icon_16x16.png" \
)

# composite every matching png file in baselayer and upper layer and put into
#   output_iconset dir
for this_icon in ${iconset_files[*]}; do
    echo $this_icon
    gm composite $upperlayer_iconset/$this_icon $baselayer_iconset/$this_icon $output_iconset/$this_icon
done

# write out final icns file
iconutil -c icns -o $output_icns $output_iconset

# remove tempdir
rm -rf $mytempdir
