#!/bin/bash

# Copyright 2017-2018 Matthew A. Clapp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# simple usage info
if [ "$#" -lt 3 ]; then
    echo "Usage: $0 <baselayer>.ico <upperlayer>.ico <output>.ico"
    echo ""
    echo "  Composite each member image of <baselayer>.ico with"
    echo "  each member image of <upperlayer>.ico into output <output>.ico"
    exit
fi

baselayer_ico=$1
upperlayer_ico=$2
output_ico=$3

echo "Base Layer:  $baselayer_ico"
echo "Upper Layer: $upperlayer_ico"
echo "Output:      $output_ico"

# create safe temp dir
mytempdir=$(mktemp -d "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")

echo $mytempdir

# get just filenames with no dirs preceding
baselayer_ico_base=$(basename "${baselayer_ico}")
upperlayer_ico_base=$(basename "${upperlayer_ico}")
output_ico_base=$(basename "${output_ico}")

# get version of filenames with .dir suffix instead of .ico
baselayer_dir="$mytempdir/${baselayer_ico_base%.*}.dir"
upperlayer_dir="$mytempdir/${upperlayer_ico_base%.*}.dir"
output_dir="$mytempdir/${output_ico_base%.*}.dir"

echo $baselayer_dir
echo $upperlayer_dir
echo $output_dir

# create image dirs in temp dir, and make empty dir for output image dir
ico2dir "$baselayer_ico" "$baselayer_dir"
ico2dir "$upperlayer_ico" "$upperlayer_dir"
mkdir "$output_dir"

# composite every matching png file in baselayer and upper layer and put into
#   output_dir dir
for this_image_path in $baselayer_dir/*; do
    this_image=$(basename "${this_image_path}")
    echo $this_image
    gm composite $upperlayer_dir/$this_image $baselayer_dir/$this_image $output_dir/$this_image
done

# write out final ico file
iconutil -c ico -o $output_ico $output_dir

# remove tempdir
rm -rf $mytempdir
