#!/bin/bash

# Copyright 2017-2018 Matthew A. Clapp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

if [ -e virt ]; then
    echo "Directory 'virt' already exists.  Remove it before running this script"
    exit 1
fi

# make dir to hold virtual environment
mkdir virt
# python3 native venv
python3 -m venv virt
# activate virtual environment
if [ -e "virt/bin/activate" ]; then
    source virt/bin/activate
elif [ -e "virt/Scripts/activate" ]; then
    source virt/Scripts/activate
else
    echo "No virt/bin/activate or virt/Scripts/activate found. Exiting"
    exit 1
fi

# install required python packages into virtual environment
# use python3 -m pip instead of pip3, because only thing that works on
#   stupid Windows
python3 -m pip install -r requirements.txt
