#!/bin/bash

# first test if uname is present
if hash uname 2>/dev/null ; then
    # uname is present, use it to find ostype
    ostype="$(uname)"
else
    # uname is not present, where are we??
    ostype="UNKNOWN"
fi
# make sure we're on Windows
if [ "$ostype" == "Darwin" -o "$ostype" == "Linux" ] ; then
    echo "ERROR: OS is not Windows.  gen_wininstaller is only applicable to Windows"
    echo "Aborting."
    exit 1
fi

source virt/Scripts/activate

pyinstaller \
    -y \
    --paths ./marcam \
    --add-data 'marcam/marktool32.png;media' \
    --add-data 'marcam/pointer32.png;media' \
    --add-data 'marcam/marcam_help.html;media' \
    --add-data 'marcam/help_markmode_off.png;media' \
    --add-data 'marcam/help_selectmode_off.png;media' \
    marcam/marcam.py
