#!/bin/bash

if [ -e virt ]; then
    echo "Directory 'virt' already exists.  Remove it before running this script"
    exit 1
fi

# make dir to hold virtual environment
mkdir virt
# python3 native venv
python3 -m venv virt
# activate virtual environment
source virt/bin/activate
# install required python packages into virtual environment
pip3 install -r requirements.txt

# patch py2app so it doesn't start hidden
# https://bitbucket.org/ronaldoussoren/py2app/issues/140/app-starts-minimized#comment-35628007
patch virt/lib/python3.6/site-packages/py2app/bootstrap/argv_emulation.py build_scripts/argv_emulation.patch 
