#!/bin/bash

# Copyright 2017-2018 Matthew A. Clapp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# For creation of Windows icon from source image dir
# Dir should contain resolutions e.g.: 
#   icon256x256.png
#   icon64x64.png
#   icon48x48.png
#   icon40x40.png
#   icon32x32.png
#   icon24x24.png
#   icon20x20.png
#   icon16x16.png
#
# usage: gen_ico <src_image_dir> <dest_ico_file>
#
# requires imagemagick

# first test if uname is present
if hash uname 2>/dev/null ; then
    # uname is present, use it to find ostype
    ostype="$(uname)"
else
    # uname is not present, where are we??
    ostype="UNKNOWN"
fi
# make sure we're on Mac
if [ "$ostype" != "Darwin" ] ; then
    echo "ERROR: OS is not macOS.  $0 only applicable to macOS"
    echo "Aborting."
    exit 1
fi

# simple usage info
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <sourcedir> <dest_ico_file>"
    echo ""
    echo "  Convert <sourcedir> images to <dest_ico_file>"
    exit
fi

srcdir=$1
destfile=$2

convert $srcdir/icon_256x256.png $srcdir/icon_128x128.png $srcdir/icon_32x32\@2x.png $srcdir/icon_32x32.png $srcdir/icon_16x16.png $destfile
