#!/bin/bash

# Copyright 2017-2018 Matthew A. Clapp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# For creation of Mac icon from source image file
# Source image file should be 1024x1024 or larger, preferably PNG with
#   alpha channel.
# from starting image file, create icns file
#
# usage: gen_icon <src_image_file>
#
# requires graphicsmagick

# first test if uname is present
if hash uname 2>/dev/null ; then
    # uname is present, use it to find ostype
    ostype="$(uname)"
else
    # uname is not present, where are we??
    ostype="UNKNOWN"
fi
# make sure we're on Mac
if [ "$ostype" != "Darwin" ] ; then
    echo "ERROR: OS is not macOS.  gen_app only applicable to macOS"
    echo "Aborting."
    exit 1
fi

# simple usage info
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <sourcefile>.png"
    echo ""
    echo "  Convert <sourcefile>.png to <sourcefile>.icns, where "
    echo "  <sourcefile>.png is a 1024x1024 or larger png image file."
    exit
fi

# create safe temp dir
mytempdir=$(mktemp -d "${TMPDIR:-/tmp/}$(basename $0).XXXXXXXXXXXX")

srcfile=$1
srcfile_info=(`gm identify $1`)
srcfile_size=${srcfile_info[2]}
srcfile_base=${srcfile##*/}
iconset_dir=$mytempdir/${srcfile_base%.*}.iconset
icnsout_file=${srcfile%.*}.icns

echo "File:      $srcfile"
echo "Size:      $srcfile_size"

mkdir $iconset_dir

if [ $srcfile_size = "1024x1024+0+0" ]; then
    echo "Size is what we expect, 1024x1024"
    cp $srcfile $iconset_dir/icon_512x512@2x.png
else
    echo "Size is $srcfile_size, converting to 1024x1024"
    gm convert $srcfile -resize 1024x1024 $iconset_dir/icon_512x512@2x.png
fi

# create two 512x512 versions of image
gm convert $srcfile -resize 512x512 $iconset_dir/icon_512x512.png
cp $iconset_dir/icon_512x512.png $iconset_dir/icon_256x256@2x.png

# create two 256x256 versions of image
gm convert $srcfile -resize 256x256 $iconset_dir/icon_256x256.png
cp $iconset_dir/icon_256x256.png $iconset_dir/icon_128x128@2x.png

# create 128x128 version of image
gm convert $srcfile -resize 128x128 $iconset_dir/icon_128x128.png

# create 64x64 version of image
gm convert $srcfile -resize 64x64 $iconset_dir/icon_32x32@2x.png

# create two 32x32 versions of image
gm convert $srcfile -resize 32x32 $iconset_dir/icon_32x32.png
cp $iconset_dir/icon_32x32.png $iconset_dir/icon_16x16@2x.png

# create 16x16 version of image
gm convert $srcfile -resize 16x16 $iconset_dir/icon_16x16.png

# convert iconset to icns file
iconutil -c icns -o $icnsout_file $iconset_dir

# remove tempdir
rm -rf $mytempdir
