#!/bin/bash

# make sure we're on Mac
ostype="$(uname >/dev/null 2>&1)" && ostype="UNKNOWN"
if [ "$ostype" != "Darwin" ] ; then
    echo "ERROR: OS is not macOS.  gen_app only applicable to macOS"
    echo "Aborting."
    exit 1
fi

# add current git hash to VERSION_STR in const.py, saving backup file
githash=(`git rev-parse --short HEAD`)
cp marcam/const.py marcam/const.py.bak
perl -i -pe "s/VERSION_STR = .*$/VERSION_STR = \"$githash\"/" marcam/const.py

# check if const.py got corrupted
syntax_error=(`python3 -m py_compile marcam/const.py`)
if [ ! -z "$syntax_error" ]; then
    echo "gen_app corrupted marcam/const.py"
    exit 1
fi

# activate virtual environment for python
source virt/bin/activate

# build app using py2app
python3 setup.py py2app

# move back original const.py file
mv marcam/const.py.bak marcam/const.py
