#!/bin/bash

# first test if uname is present
if hash uname 2>/dev/null ; then
    # uname is present, use it to find ostype
    ostype="$(uname)"
else
    # uname is not present, where are we??
    ostype="UNKNOWN"
fi
# make sure we're on Mac
if [ "$ostype" != "Darwin" ] ; then
    echo "ERROR: OS is not macOS.  gen_dmg only applicable to macOS"
    echo "Aborting."
    exit 1
fi

# activate virtual environment for python to get dmgbuild
source virt/bin/activate

# dmgbuild
dmgbuild -s build_scripts/dmgbuild_settings.py "Marcam" dist/Marcam.dmg
