#!/bin/bash

# from:
# https://stackoverflow.com/questions/96882/how-do-i-create-a-nice-looking-dmg-for-mac-os-x-using-command-line-tools

thispwd=`pwd -P`

if [ -e dist/dmg_dir ]; then
    echo "dist/dmg_dir already exists"
else
    echo "creating dist/dmg_dir"
    mkdir dist/dmg_dir
fi

cp -a dist/Marcam.app dist/dmg_dir/

srcfolder="dist/dmg_dir"
volname="Marcam"
fs="HFS+"
size="200000"

# create disk image
hdiutil create -srcfolder "${srcfolder}" -volname "${volname}" -fs "${fs}" \
      -fsargs "-c c=64,a=16,e=16" -format UDRW -size ${size}k pack.temp.dmg

# open disk image
echo "Device name:"
device=$(hdiutil attach -readwrite -noverify -noautoopen "pack.temp.dmg" | egrep '^/dev/')

# DEBUG DELETE ME
echo $device

# pause to workaround "Can't get disk Marcam" (-1728) issue
sleep 2

# put icns in path for custom volume icon
cp misc/marcam_drive.icns /Volumes/${volname}/.VolumeIcon.icns
# set bit to indicate custom icon
#   SetFile is "deprecated" but man page doesn't say what to do instead !
SetFile -a C /Volumes/${volname}

# copy arrow.png to volume as hidden file
mkdir /Volumes/${volname}/.background
cp misc/arrow.png /Volumes/${volname}/.background/arrow.png

echo '
    tell application "Finder"
        tell disk "'${volname}'"
            open
            set current view of container window to icon view
            set toolbar visible of container window to false
            set statusbar visible of container window to false
            set the bounds of container window to {500, 400, 1000, 650}
            set theViewOptions to the icon view options of container window
            set arrangement of theViewOptions to not arranged
            set icon size of theViewOptions to 128
            set background picture of theViewOptions to file ".background:arrow.png"
            make new alias file at container window to POSIX file "/Applications" with properties {name:"Applications"}
            set position of item "Marcam.app" of container window to {100, 100}
            set position of item "Applications" of container window to {375, 100}
            update without registering applications
            delay 5
            close
        end tell
    end tell
' | osascript

# make all files read-only in volume (necessary?)
chmod -Rf go-w /Volumes/"${volname}"
# 2 syncs? really?
sync
sync

# eject volume
hdiutil detach  /Volumes/"${volname}"

hdiutil convert "pack.temp.dmg" -format UDZO -imagekey zlib-level=9 -o "dist/Marcam.dmg"

# clean up
rm pack.temp.dmg
rm -rf dist/dmg_dir
