#!/bin/bash

# make sure we're on Windows
ostype="$(uname >/dev/null 2>&1)" && ostype="UNKNOWN"
if [ "$ostype" == "Darwin" -o "$ostype" == "Linux" ] ; then
    echo "ERROR: OS is not Windows.  gen_wininstaller is only applicable to Windows"
    echo "Aborting."
    exit 1
fi

makensis build_scripts/marcam.nsi
