#!/bin/bash

# make sure we're on Windows
ostype="$(uname >/dev/null 2>&1)" && ostype="UNKNOWN"
if [ "$ostype" == "Darwin" -o "$ostype" == "Linux" ] ; then
    echo "ERROR: OS is not Windows.  gen_winexe only applicable to Windows"
    echo "Aborting."
    exit 1
fi

source virt/Scripts/activate

pyinstaller \
    -y \
    --paths ./marcam \
    --add-data 'marcam/marktool32.png;media' \
    --add-data 'marcam/pointer32.png;media' \
    --add-data 'marcam/marcam_help.html;media' \
    --add-data 'marcam/help_markmode_off.png;media' \
    --add-data 'marcam/help_selectmode_off.png;media' \
    marcam/marcam.py
