#!/bin/bash

# Copyright 2017-2018 Matthew A. Clapp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# first test if uname is present
if hash uname 2>/dev/null ; then
    # uname is present, use it to find ostype
    ostype="$(uname)"
else
    # uname is not present, where are we??
    ostype="UNKNOWN"
fi
# make sure we're on Mac
if [ "$ostype" != "Darwin" ] ; then
    echo "ERROR: OS is not macOS.  gen_dmg only applicable to macOS"
    echo "Aborting."
    exit 1
fi

# activate virtual environment for python to get dmgbuild
source virt/bin/activate

# dmgbuild
dmgbuild -s build_scripts/dmgbuild_settings.py "Marcam" dist/Marcam.dmg
