#!/usr/bin/env python3

import re
import shutil
import subprocess
import sys

# cheap argv processing to look for -a
if len(sys.argv) > 1 and sys.argv[1] == "-a":
    extra_arg = ["-a"]
else:
    extra_arg = []

def do_uname():
    returnval = subprocess.run(
            ["uname"] + extra_arg,
            stderr=subprocess.DEVNULL,
            stdout=subprocess.PIPE
            )
    mystdout = returnval.stdout.decode('utf-8')
    print(mystdout, end="")

def do_systeminfo():
    returnval = subprocess.run(
            "systeminfo",
            stderr=subprocess.DEVNULL,
            stdout=subprocess.PIPE
            )
    mystdout = returnval.stdout.decode('utf-8')

    out_str1 = None
    out_str2 = None

    for line in mystdout.split("\r\n"):
        osname_re = re.search(r"^OS Name:\s+(\S.+)$", line)
        if osname_re:
            out_str1 = osname_re.group(1)

        osver_re = re.search(r"^OS Version:\s+(\S.+)$", line)
        if osver_re:
            out_str2 = osver_re.group(1)

        if out_str1 and out_str2:
            break

    if extra_arg==["-a"]:
        print(out_str1 + " Version " + out_str2)
    else:
        print(out_str1)


if __name__ == "__main__":
    if shutil.which('systeminfo') is not None:
        do_systeminfo()
    elif shutil.which('uname') is not None:
        do_uname()
    else:
        print("UNKNOWN")
