#!/bin/bash

# vec2png
# convert square vector image file (e.g. svg or eps) to png file
#
# vec2png <resolution> <in_file1> [<in_file2> ...]
#
# where output resolution is <resolution>px x <resolution>px

if [[ $# -lt 2 ]]; then
    echo "Usage:"
    echo "    $0 <resolution> <in_file1> [<in_file2> ...]"
    echo ""
    echo "Convert each input image file to png file with output"
    echo "  resolution <resolution>px x <resolution>px"
    exit 1
fi

resolution=$1
shift
echo Converting to $resolution x $resolution
for infile in $@
do
    if [[ $infile == *".svg" ]]; then
        outfile=${infile%svg}png
        echo "$infile -> $outfile"
        convert -colorspace sRGB -background transparent $infile -filter box \
            -resize $resolutionx$resolution PNG32:$outfile
    fi
    if [[ $infile == *".eps" ]]; then
        outfile=${infile%eps}png
        echo "$infile -> $outfile"
        convert -colorspace sRGB -background transparent $infile -filter box \
            -resize $resolutionx$resolution PNG32:$outfile
    fi
done


