#!/bin/bash

# Copyright 2017-2018 Matthew A. Clapp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# activate virtual environment
if [ -e "virt_test/bin/activate" ]; then
    source virt_test/bin/activate
elif [ -e "virt_test/Scripts/activate" ]; then
    source virt_test/Scripts/activate
else
    echo "No virt_test/bin/activate or virt_test/Scripts/activate found. Exiting"
    exit 1
fi

# add marcam directory to python paths, so individual *.py files of marcam
#   can be imported
export PYTHONPATH='marcam/'

extra_pylint_args="$1"

# if uname is present, use it to find ostype
if hash uname 2>/dev/null && [ "$ostype" != "Darwin" ] ; then
    extra_pylint_args+=' --ignored-modules=wx,wx.*,win32pipe,win32file,pywintypes'
fi

# run tests
python3 -m pylint $extra_pylint_args --rcfile=scripts/pylintrc_make marcam/
