#!/bin/bash

# Copyright 2017-2018 Matthew A. Clapp
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# simple usage info
if [ "$#" -lt 1 ]; then
    echo "Usage: $0 <sourcefile>.ico [outputdir]"
    echo ""
    echo "  Convert <sourcefile>.ico to directory of PNG images."
    echo "  If argument <outputdir> is present, use as output dir."
    echo "  if argument <outputdir> is not present, output to"
    echo "  dir: <sourcefile>.dir"
    exit
fi

input_ico=$1
if [[ -z "$2" ]]; then
    output_dir="${1%.ico}"
else
    output_dir="$2"
fi

mkdir "${output_dir}"
convert "${input_ico}" "${output_dir}/icon.png"

for img_file in ${output_dir}/*
do
    img_file_dir=$(dirname "${img_file}")
    img_res_id=$(identify "${img_file}" | perl -lpe 's/^.+PNG\s(\S+).+$/\1/')
    img_file_new="${img_file_dir}/icon_${img_res_id}.png"
    mv ${img_file} ${img_file_new}
done

echo Wrote ${input_ico} to directory ${output_dir}/
