#!/usr/bin/env python3

import sys
import os
import struct
import time
import array
from PIL import Image
import biorad1sc_reader


def convert_file(filename):
    # get full path to filename, and its dir
    filename = os.path.realpath(filename)
    filedir = os.path.dirname(filename)

    # open output text file to write info
    try:
        out_fh = open(os.path.join(filedir,"dump.txt"),"w")
    except:
        print("Error opening dump.txt", file=sys.stderr)
        raise

    # new reader object
    reader1sc = biorad1sc_reader.Reader(filename)

    img_meta = reader1sc.get_img_metadata()
    print("get_img_metadata:", file=out_fh)
    print(img_meta, file=out_fh)

    img_meta2 = reader1sc.get_img_metadata2()
    print("get_img_metadata2:", file=out_fh)
    for collection in img_meta2:
        print("\nCollection: %s"%collection, file=out_fh)
        coll = img_meta2[collection]
        for item in coll:
            print(" "*4 + "Item: %s"%item, file=out_fh)
            coll_item = coll[item]
            for region in coll_item:
                print(" "*8 + "Region: %s"%region, file=out_fh)
                print(" "*8 + repr(coll_item[region]), file=out_fh)

    (img_x, img_y, img_data) = reader1sc.get_img_data(invert=True)
    print("get_img_data:", file=out_fh)
    print(img_x, file=out_fh)
    print(img_y, file=out_fh)
    print(len(img_data), file=out_fh)
    print(min(img_data), file=out_fh)
    print(max(img_data), file=out_fh)

    # output plain tiff
    print("test1.tif", file=sys.stderr)
    reader1sc.save_img_as_tiff(
            os.path.join(filedir, "test1.tif"),
            invert=True
            )

    # output scaled tiff
    print("test1sc1.0.tif", file=sys.stderr)
    reader1sc.save_img_as_tiff_sc(
            os.path.join(filedir, "test1sc1.0.tif"),
            invert=True
            )

    # output scaled tiff
    print("test1sc0.6.tif", file=sys.stderr)
    reader1sc.save_img_as_tiff_sc(
            os.path.join(filedir, "test1sc0.6.tif"),
            imgsc=0.6,
            invert=True
            )

    # output scaled tiff
    print("test1sc0.4.tif", file=sys.stderr)
    reader1sc.save_img_as_tiff_sc(
            os.path.join(filedir, "test1sc0.4.tif"),
            imgsc=0.4,
            invert=True
            )

    # output scaled tiff
    print("test1sc0.2.tif", file=sys.stderr)
    reader1sc.save_img_as_tiff_sc(
            os.path.join(filedir, "test1sc0.2.tif"),
            imgsc=0.2,
            invert=True
            )

    # output 16-bit tiff test gradient
    gradx = 1000
    grady = 1000
    img_data=[]
    min_ = 0
    max_ = 2**16-1
    for i in range(gradx*grady):
        img_data.append(int(i/(gradx*grady)*(max_-min_) + min_))
    img_data_pilbytes = array.array("H",img_data).tobytes() 
    img_out = Image.new('I;16',(gradx,grady))
    img_out.frombytes(img_data_pilbytes)
    img_out.save("gradient.tif")


def main(args):
    for filename in args:
        convert_file(filename)


if __name__ == "__main__":
    main(sys.argv[1:])
    exit(0)
